### ISSUE TITLE
Modifying state during view update, this will cause undefined behavior.

### ISSUE THREAD

**Issue by foolbear** [kenmueller/TextView#10]
public func textViewDidChange(_ textView: UITextView) {
    parent.text = textView.text
}

**Comment by kenmueller** [comment]
Needs a bit more explanation. I haven't gotten this warning in my tests.

**Comment by ejensen** [comment]
@kenmueller The runtime issue can be triggered reliably when entering text in the simulator with the "All Runtime Issues" breakpoint enabled
<img width="1464" alt="runtime-issue" src="https://user-images.githubusercontent.com/915431/95494666-1a1d5e80-0953-11eb-9683-ef55985231ce.png">
