### ISSUE TITLE
Reference to property 'isEditing' in closure requires explicit 'self.....

### ISSUE THREAD

**Issue by ServicePal** [kenmueller/TextView#12]
Just moved from 1.4.0 -> 1.4.3 and get compilation error. I see there are recent changes. Is there another fix coming?

<img width="995" alt="Screen Shot 2020-04-10 at 7 49 25 PM" src="https://user-images.githubusercontent.com/8471863/79033755-b06bf580-7b65-11ea-8eca-549e357b380c.png">

Maybe I just have bad timing.

**Comment by kenmueller** [comment]
So sorry. I accepted a pull request without testing it first, won't do that again.

https://github.com/kenmueller/TextView/releases/tag/v1.4.4
