### ISSUE TITLE
How to remove the padding in Textfield

### ISSUE THREAD

**Issue by morad** [kenmueller/TextView#23]
Hello,

Great work on this small but yet effective class. 

I've noticed my text is not fully aligned to the left. I was able to align the placeholder text with:

placeholderHorizontalPadding: 0

But for life of me, I can't do the same for the input text itself..  any tip on this?

<img width="265" alt="Screen Shot 2020-05-25 at 6 06 04 PM" src="https://user-images.githubusercontent.com/66266/82824680-6b501880-9eb2-11ea-8a6f-1c4a223cd21c.png">

**Comment by kenmueller** [comment]
Hey, thanks for letting me know about this! I just submitted a new release (https://github.com/kenmueller/TextView/releases/tag/v1.4.6) that fixes this. You can adjust the `textHorizontalPadding` and `textVerticalPadding` in the constructor, and if it suits you, you can make these values negative. Hope this helps!
