### ISSUE TITLE
Like a TextField

### ISSUE THREAD

**Issue by jiasenlin** [kenmueller/TextView#25]
First, thanks very much for the library, it's very helpful!

I am new to mobile development and swiftui, a noob question please
Is it possible to use TextView as TextField, like:
1. Only allow user to input one line of text
2. When user hit return, close keyboard and commit text

**Comment by kenmueller** [comment]
Why wouldn't a TextField work in this situation? If for some reason you can't use one, just add a `set` listener to your `Binding` text variable, and if it contains a `\n`, set `isEditing = false` and do what you need to do.

**Comment by kenmueller** [comment]
And also make sure that you don't commit the `\n` either because then the TextView will be unusable in the future.

**Comment by jiasenlin** [comment]
TextField doesn't support Chinese input.
I tried set listener like this, seems it won't be triggered while I typing or return :(
```
    @State var searchText: String = "" {
        willSet{
            print("willSet: newValue =\(newValue)")
        }
        didSet{
            print("didSet: oldValue=\(oldValue)")
        }
    }

```
But you question makes sense. 
I probably should use UITextField with UIViewRepresentable like you did on UITextView
