### ISSUE TITLE
Using returnKey

### ISSUE THREAD

**Issue by JonasDeichelmann** [kenmueller/TextView#27]
Hi,

the TextView has the option to set the returnKey and use it, for example in Forms to jump to the next TextView or TextField.

Cheers,
Jonas

**Comment by kenmueller** [comment]
There was a PR that added a returnKey option, did that fix your issue?

**Comment by JonasDeichelmann** [comment]
@kenmueller 
Thank you for your reply. Could you refer the PR and explain how to use the returnKey Option?

**Comment by kenmueller** [comment]
https://github.com/kenmueller/TextView/pull/28

You can pass in `returnType: UIReturnKeyType` to the constructor.

**Comment by kenmueller** [comment]
Accidentally closed, sorry.

**Comment by jamesyorke** [comment]
Any chance you could add a new version with this return key addition?

The latest version I can see in SPM is 1.4.7.

**Comment by kenmueller** [comment]
Yep! Sorry about that. https://github.com/kenmueller/TextView/releases/tag/v1.4.8
