### ISSUE TITLE
Tapping on placeholder text doesn't add caret.

### ISSUE THREAD

**Issue by james-william-r** [kenmueller/TextView#35]
Not sure if this has always been the case, but if the TextView has placeholder text, users are forced to tap on the empty space, they cannot tap the placeholder to start typing. This is especially an issue with longer placeholders, it makes the box seem un-responsive and difficult to edit.

Would really appreciate a fix, or workaround! 🙏😊

**Comment by ejensen** [comment]
PR #36 should fix this issue

**Comment by james-william-r** [comment]
Thanks a tonne, @ejensen! We'll wait for it to be merged. 😊

**Comment by james-william-r** [comment]
Weirdly, we're seeing this issue pop-up again, but only in once instance, where we have a `TextView` within a `.sheet `. 🤷
