### ISSUE TITLE
add a placeholder

### ISSUE THREAD

**Issue by TomFrank** [kenmueller/TextView#5]
thanks for your work
and would you please add a placeholder for the TextView?
just like this
![image](https://user-images.githubusercontent.com/7746180/71542043-5f603900-299c-11ea-9f95-fc834220217b.png)
thx

**Comment by kenmueller** [comment]
So sorry, been busy with other work. I'll get to this ASAP.

**Comment by ServicePal** [comment]
Came here looking for just that.

**Comment by kenmueller** [comment]
Sorry about the wait. I've added a placeholder.
