### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by foolbear** [kenmueller/TextView#9]
1. @State isEditing = true, crash.
2. it's hard to become edit mode if placeholder present, no response tap on the placeholder.
3. when text is empty(placeholder present), can not show copy/paste context menu if long pressed. you must long pressed on the blank(not placeholder).
4. placeholder cannot scroll.
5. just append string in the end, can not insert.

**Comment by foolbear** [comment]
1 becomeFirstResponder/resignFirstResponder not necessary.
2,3 because placeholder cover the textview, change their position in zstack please.
4 not important
5 IT'S critical: because of updateUIView. For example, there are some words(eg, "Hello world") in the textview, I move the cursor in the middle of the text(after e), then input "z", it's OK("Hezllo world"), but  updateUIView move the cursor to the end of text. I have not ideal now.

**Comment by kenmueller** [comment]
Hmm. That's strange why you're getting these problems, most of these work fine except for the placeholder not scrolling. That shouldn't be an issue though because you can only see the placeholder when there is no text. Inserting works, just tested it. The placeholder text also does not allow hit testing, so you can tap through it. Can you show a small demo since I'm not able to reproduce the issues?

**Comment by foolbear** [comment]
easy, please set placeholder a very long string.
How about Q5, any ideals?

**Comment by maail** [comment]
@kenmueller I'm having the same issue with the placeholder not being tappable. I see that allHitTesting is false, but it's not working the way it should. Might be a SwiftUI bug. 

See attached Gif for example

![Screen-Recording-2020-04-11-at-9 01 44-AM](https://user-images.githubusercontent.com/955823/79031724-5bff5f00-7bd3-11ea-8b19-7234d61f59fa.gif)

**Comment by kenmueller** [comment]
This must've come up in the new SwiftUI update, which is unfortunate. For the time being, I've fixed it by adding a tap gesture to the placeholder that sets the UITextView as the first responder.

https://github.com/kenmueller/TextView/releases/tag/v1.4.1

**Comment by maail** [comment]
@kenmueller Great. Thanks. I've fixed the crash mentioned by @foolbear's issue 1 and sent a PR

**Comment by kenmueller** [comment]
@maail Oops. Seems like some changes were mixed around. I've re-pushed with the hit testing fix.
